### ISSUE TITLE
.toEmit only accepts a single payload, but $emit allows emission of multiple payload values

### ISSUE THREAD

**Issue by gogojosh** [hmsk/jest-matcher-vue-test-utils#28]
As we discussed when we investigated this together, it seems like `$emit` is able to accept multiple payload values, but we're only expecting a single payload value in the function signature definition for `.toEmit`.

This causes TS compilation errors when trying to expect multiple payload values from `toEmit`.

**Comment by hmsk** [comment]
Thanks for the report Josh!
Fixed the problem (and support by `toHaveEmitted` too), then released as v1.4.0. I will bring to Indiegogo after adding Vuex stuff in #24 😉
