### ISSUE TITLE
jest^24 support

### ISSUE THREAD

**Issue by sobolevn** [hmsk/jest-matcher-vue-test-utils#93]
Hi, the latest version of `jest` (`^24.8.0`) raises a warning when used with your plugin:

```
npm WARN jest-matcher-vue-test-utils@1.5.1 requires a peer of jest@^22.0.0 || ^23.0.0 but none is installed. You must install peer dependencies yourself.
```

Can we update `jest` version to the latest one?

**Comment by hmsk** [comment]
Thanks for reporting. I totally forgot about that I specified peerDep.
As development of this module, I intended to block using "24" in devDependencies, since new version of vue-jest comes. But peer should be fine. So I will check and update asap.

**Comment by sobolevn** [comment]
I have already sent a PR to help you 🙂

**Comment by sobolevn** [comment]
Yes, it works! https://github.com/wemake-services/wemake-vue-template/pull/1159
